language: node_js
node_js:
  - 10.16.3
before_script:
  - yarn install
before_deploy:
  - yarn build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: oust.concept41.com
    skip_cleanup: true
    local_dir: build
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: "oust_getGame"
    region: "us-east-1"
    role: "arn:aws:iam::072629470284:role/service-role/oust_getGame-role-8cf5pk98"
    handler_name: "handler"
    runtime: "nodejs12.x"
    zip: src/lambdas/getGame.js
